/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaz;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Cassandra
 */
public class frameAlmacen extends javax.swing.JInternalFrame
{

    /**
     * Creates new form frameClientes
     */
    public frameAlmacen()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtClave = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        txtClaveReg = new javax.swing.JTextField();
        txtRegistro = new javax.swing.JTextField();
        txtPrecauciones = new javax.swing.JTextField();
        txtEfectos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAdministracion = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBorder(null);
        setTitle("Almacen");
        setPreferredSize(new java.awt.Dimension(700, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(680, 530));
        jPanel1.setPreferredSize(new java.awt.Dimension(680, 530));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel6.setText("Clave:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jButton2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jButton2.setText("Detalles");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        txtClave.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtClave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtClaveActionPerformed(evt);
            }
        });
        jPanel1.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 370, 28));

        jButton5.setBackground(new java.awt.Color(51, 255, 51));
        jButton5.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String []
            {
                "Nombre", "Fabricante", "Fecha de vencimiento", "No. Registro sanitario", "Vía de administración", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 660, 320));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 530));

        jTabbedPane1.addTab("Consulta", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel1.setText("Clave:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel2.setText("Precauciones y advertencias:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel3.setText("Precio:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel4.setText("Fecha de vencimiento:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 20));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel5.setText("Vía de administración:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, 20));

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        txtPrecio.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtPrecioActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 150, 28));

        txtClaveReg.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtClaveReg.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtClaveRegActionPerformed(evt);
            }
        });
        jPanel2.add(txtClaveReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 150, 28));

        txtRegistro.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtRegistro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtRegistroActionPerformed(evt);
            }
        });
        jPanel2.add(txtRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 180, 30));

        txtPrecauciones.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtPrecauciones.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtPrecaucionesActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrecauciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 260, 110));

        txtEfectos.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtEfectos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtEfectosActionPerformed(evt);
            }
        });
        jPanel2.add(txtEfectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 260, 110));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel7.setText("Nombre:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel12.setText("Efectos secundarios:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel13.setText("registro sanitario:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, 20));

        txtNombre.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 190, 28));

        jLabel14.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel14.setText("Número de");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, 20));

        txtAdministracion.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtAdministracion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtAdministracionActionPerformed(evt);
            }
        });
        jPanel2.add(txtAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 190, 30));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 190, 30));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 530));

        jTabbedPane1.addTab("Registro", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtPrecioActionPerformed
    {//GEN-HEADEREND:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtClaveRegActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtClaveRegActionPerformed
    {//GEN-HEADEREND:event_txtClaveRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveRegActionPerformed

    private void txtPrecaucionesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtPrecaucionesActionPerformed
    {//GEN-HEADEREND:event_txtPrecaucionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecaucionesActionPerformed

    private void txtRegistroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtRegistroActionPerformed
    {//GEN-HEADEREND:event_txtRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroActionPerformed

    private void txtEfectosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtEfectosActionPerformed
    {//GEN-HEADEREND:event_txtEfectosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEfectosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        String clave = txtClaveReg.getText();
        String nombre = txtNombre.getText();
        String precio = txtPrecio.getText();
//        String fecha = txtFecha.getText();
        String administracion = txtAdministracion.getText();
        String registro = txtRegistro.getText();
        String efectos = txtEfectos.getText();        
        String precauciones = txtPrecauciones.getText();        
        
        String expClave = "[0-9]{5,20}";
        String expNombre = "[a-zA-z]{10,50}";
        String expPrecio = "$[0-9]*";
        String expFecha = "^(0?[1-9]|[12][0-9]|30)-(0?[1-9]|1[012])-((20)\\d{2})$";
        String expAdministracion = "[a-zA-Z]*";
        String expRegistro = "[0-9]{1,6}";
        String expEfectos = "[a-zA-z]{10,100}";        
        String expPrecauciones = "[a-zA-z]{10,50}";        
        
        Pattern patClave = Pattern.compile(expClave);
        Pattern patNombre = Pattern.compile(expNombre);
        Pattern patPrecio = Pattern.compile(expPrecio);
        Pattern patFecha = Pattern.compile(expFecha);
        Pattern patAdministracion = Pattern.compile(expAdministracion);
        Pattern patRegistro = Pattern.compile(expRegistro);
        Pattern patEfectos = Pattern.compile(expEfectos);
        Pattern patPrecauciones = Pattern.compile(expPrecauciones);
        
        Matcher matchClave = patClave.matcher(clave);
        Matcher matchNombre = patNombre.matcher(nombre);
        Matcher matchPrecio = patPrecio.matcher(precio);
//        Matcher matchFecha = patFecha.matcher(fecha);
        Matcher matchAdministracion = patAdministracion.matcher(administracion);
        Matcher matchRegistro = patRegistro.matcher(registro);
        Matcher matchEfectos = patEfectos.matcher(efectos);
        Matcher matchPrecauciones = patPrecauciones.matcher(precauciones);
        
        boolean validaClave = matchClave.matches();
        boolean validaNombre = matchNombre.matches();
        boolean validaPrecio = matchPrecio.matches();
//        boolean validaFecha = matchFecha.matches();
        boolean validaAdministracion = matchAdministracion.matches();
        boolean validaRegistro = matchRegistro.matches();
        boolean validaEfectos = matchEfectos.matches();
        boolean validaPrecauciones = matchPrecauciones.matches();
        
        if (!validaClave && !validaNombre && !validaPrecio && /*!validaFecha &&*/ !validaAdministracion && !validaRegistro && !validaEfectos && !validaPrecauciones)
        {
            JOptionPane.showMessageDialog(frameAlmacen.this, "Hay campos vacios o incorrectos", "Faltan datos", JOptionPane.WARNING_MESSAGE);
        } else
        {
            JOptionPane.showMessageDialog(frameAlmacen.this, "Agregando Producto...", "Registrar", JOptionPane.INFORMATION_MESSAGE);
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(frameAlmacen.this, "Obteniendo mas detalles...", "Detalles", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtClaveActionPerformed
    {//GEN-HEADEREND:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNombreActionPerformed
    {//GEN-HEADEREND:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtAdministracionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtAdministracionActionPerformed
    {//GEN-HEADEREND:event_txtAdministracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdministracionActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        if (txtClave.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(frameAlmacen.this, "Ingrese una clave", "Clave vacia", JOptionPane.WARNING_MESSAGE);
        } else
        {
            String clave = txtClave.getText();
            
            String exRClave = "[0-9]{5,20}";
            
            Pattern pattClave = Pattern.compile(exRClave);
            Matcher matchClave = pattClave.matcher(clave);
            
            boolean valClave = matchClave.matches();
            
            if (!valClave)
            {
                JOptionPane.showMessageDialog(frameAlmacen.this, "La clave ingresada es incorrecta", "Clave incorrecta", JOptionPane.WARNING_MESSAGE);
            } else
            {
                JOptionPane.showMessageDialog(frameAlmacen.this, "Buscando...", "Procesando Busqueda", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAdministracion;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtClaveReg;
    private javax.swing.JTextField txtEfectos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecauciones;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRegistro;
    // End of variables declaration//GEN-END:variables
}
