/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaz;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import static interfaz.vtnIngreso.tipoUsuario;

/**
 *
 * @author Cassandra
 */
public class frameAdmin extends javax.swing.JInternalFrame
{

    /**
     * Creates new form frameAdmin
     */
    public frameAdmin()
    {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelRegistro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtNombre = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtDomicilio = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        passwordPrim = new javax.swing.JPasswordField();
        passwordConf = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        registrar = new javax.swing.JButton();
        limpia = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        panelEmpleados = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.png"))); // NOI18N

        setTitle("Alta de empleados");
        setPreferredSize(new java.awt.Dimension(700, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("ID:");
        panelRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario33.png"))); // NOI18N
        panelRegistro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Nombre completo:");
        panelRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Domicilio:");
        panelRegistro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Contraseña:");
        panelRegistro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Usuario:");
        panelRegistro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Confirmar contraseña:");
        panelRegistro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Teléfono:");
        panelRegistro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRadioButton1.setText("Administrador");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButton1ActionPerformed(evt);
            }
        });
        panelRegistro.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRadioButton2.setText("Ventas");
        panelRegistro.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));
        panelRegistro.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 310, 30));

        txtID.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtIDActionPerformed(evt);
            }
        });
        panelRegistro.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 120, 30));

        txtDomicilio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtDomicilioActionPerformed(evt);
            }
        });
        panelRegistro.add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 310, 30));
        panelRegistro.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 190, 30));

        passwordPrim.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                passwordPrimActionPerformed(evt);
            }
        });
        panelRegistro.add(passwordPrim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 150, 30));

        passwordConf.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                passwordConfActionPerformed(evt);
            }
        });
        panelRegistro.add(passwordConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 160, 30));

        txtUsuario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtUsuarioActionPerformed(evt);
            }
        });
        panelRegistro.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 310, 30));

        registrar.setBackground(new java.awt.Color(51, 255, 51));
        registrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                registrarActionPerformed(evt);
            }
        });
        panelRegistro.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        limpia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        limpia.setText("Limpiar");
        limpia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                limpiaActionPerformed(evt);
            }
        });
        panelRegistro.add(limpia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.png"))); // NOI18N
        panelRegistro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        jTabbedPane1.addTab("Registro", panelRegistro);

        panelEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel12.setText("Clave:");
        panelEmpleados.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        txtClave.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        txtClave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtClaveActionPerformed(evt);
            }
        });
        panelEmpleados.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 370, 28));

        jButton5.setBackground(new java.awt.Color(51, 255, 51));
        jButton5.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });
        panelEmpleados.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String []
            {
                "ID", "Nombre", "Domicilio", "Usuario", "Télefono", "Puesto"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        panelEmpleados.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 660, 320));

        jButton2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jButton2.setText("Detalles");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        panelEmpleados.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.png"))); // NOI18N
        panelEmpleados.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 530));

        jTabbedPane1.addTab("Empleados", panelEmpleados);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));
        jTabbedPane1.getAccessibleContext().setAccessibleName("Empleados");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtUsuarioActionPerformed
    {//GEN-HEADEREND:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_registrarActionPerformed
    {//GEN-HEADEREND:event_registrarActionPerformed
        if (txtID.getText().trim().isEmpty() || txtNombre.getText().trim().isEmpty() || txtDomicilio.getText().trim().isEmpty() || txtUsuario.getText().trim().isEmpty()
                || txtTelefono.getText().trim().isEmpty() || passwordPrim.getPassword().length == 0 || passwordConf.getPassword().length == 0
                || (!jRadioButton1.isSelected() && !jRadioButton2.isSelected()))
        {
            String id = txtID.getText();
            String nombre = txtNombre.getText();
            String direccion = txtDomicilio.getText();
            String usuario = txtUsuario.getText();
            String telefono = txtTelefono.getText();
            String contra = passwordPrim.getText();
            String contraConf = passwordConf.getText();

            String expID = "[0-9]{3}";
            String expNombre = "[A-Za-z]{20,50}";
            String expDireccion = "[a-zA-Z0-9]{100}";
            String expUsuario = "[a-zA-Z0-9]{10}";
            String expTelefono = "[0-9]{10}";
            String expContra = "[0-9a-z]{6}";
            String expContraConf = "[0-9a-z]{6}";

            Pattern patID = Pattern.compile(expID);
            Pattern patNombre = Pattern.compile(expNombre);
            Pattern patDireccion = Pattern.compile(expDireccion);
            Pattern patUsuario = Pattern.compile(expUsuario);
            Pattern patTelefono = Pattern.compile(expTelefono);
            Pattern patContra = Pattern.compile(expContra);
            Pattern patContraConf = Pattern.compile(expContraConf);

            Matcher matchID = patID.matcher(id);
            Matcher matchNombre = patNombre.matcher(nombre);
            Matcher matchDireccion = patDireccion.matcher(direccion);
            Matcher matchUsuario = patUsuario.matcher(usuario);
            Matcher matchTelefono = patTelefono.matcher(telefono);
            Matcher matchContra = patContra.matcher(contra);
            Matcher matchContraConf = patContraConf.matcher(contraConf);

            boolean validaID = matchID.matches();
            boolean validaNombre = matchNombre.matches();
            boolean validaDireccion = matchDireccion.matches();
            boolean validaUsuario = matchUsuario.matches();
            boolean validaTelefono = matchTelefono.matches();
            boolean validaContra = matchContra.matches();
            boolean validaContraConf = matchContraConf.matches();

            if (!validaID && !validaNombre && !validaDireccion && !validaUsuario && !validaTelefono && !validaContra && !validaContraConf)
            {
                JOptionPane.showMessageDialog(frameAdmin.this, "Hay campos vacios y/o están incorrectos", "Faltan datos", JOptionPane.WARNING_MESSAGE);
            }else
            {
                if (jRadioButton1.isSelected() || jRadioButton2.isSelected())
                {
                    tipoUsuario = (jRadioButton1.isSelected()) ? 1 : 0;                                        
                } else
                {
                    JOptionPane.showMessageDialog(frameAdmin.this, "Seleccione el tipo de usuario", "Faltan Tipo Usuario", JOptionPane.WARNING_MESSAGE);
                }
            }
        } else
        {
            JOptionPane.showMessageDialog(frameAdmin.this, "Registrando...", "Registrar", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void limpiaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_limpiaActionPerformed
    {//GEN-HEADEREND:event_limpiaActionPerformed
        limpiar();
    }//GEN-LAST:event_limpiaActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtIDActionPerformed
    {//GEN-HEADEREND:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtDomicilioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtDomicilioActionPerformed
    {//GEN-HEADEREND:event_txtDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomicilioActionPerformed

    private void passwordPrimActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_passwordPrimActionPerformed
    {//GEN-HEADEREND:event_passwordPrimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordPrimActionPerformed

    private void passwordConfActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_passwordConfActionPerformed
    {//GEN-HEADEREND:event_passwordConfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordConfActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton1ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtClaveActionPerformed
    {//GEN-HEADEREND:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        if (txtClave.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(frameAdmin.this, "Ingrese una clave", "Clave vacia", JOptionPane.WARNING_MESSAGE);
        } else
        {
            String clave = txtClave.getText();

            String exRClave = "[0-9]{5,20}";

            Pattern pattClave = Pattern.compile(exRClave);
            Matcher matchClave = pattClave.matcher(clave);

            boolean valClave = matchClave.matches();

            if (!valClave)
            {
                JOptionPane.showMessageDialog(frameAdmin.this, "La clave ingresada es incorrecta", "Clave incorrecta", JOptionPane.WARNING_MESSAGE);
            } else
            {
                JOptionPane.showMessageDialog(frameAdmin.this, "Buscando...", "Procesando Busqueda", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(frameAdmin.this, "Obteniendo mas detalles...", "Detalles", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed
    private void limpiar()
    {
        txtID.setText("");
        txtNombre.setText("");
        txtDomicilio.setText("");
        txtUsuario.setText("");
        txtTelefono.setText("");
        passwordPrim.setText("");
        passwordConf.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton limpia;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JPasswordField passwordConf;
    private javax.swing.JPasswordField passwordPrim;
    private javax.swing.JButton registrar;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
