/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vtnF;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import static vtnF.vtnIngreso.tipoUsuario;

/**
 *
 * @author Cassandra
 */
public class frameAdmin extends javax.swing.JInternalFrame
{

    /**
     * Creates new form frameAdmin
     */
    public frameAdmin()
    {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtNombre = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtDomicilio = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        passwordPrim = new javax.swing.JPasswordField();
        passwordConf = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        registrar = new javax.swing.JButton();
        limpia = new javax.swing.JButton();

        setTitle("Alta de empleados");
        setPreferredSize(new java.awt.Dimension(620, 420));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario33.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Nombre completo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Domicilio:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Contraseña:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Usuario:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Confirmar contraseña:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Teléfono:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRadioButton1.setText("Administrador");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRadioButton2.setText("Ventas");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 310, 30));

        txtID.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 30));

        txtDomicilio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtDomicilioActionPerformed(evt);
            }
        });
        getContentPane().add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 310, 30));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 190, 30));

        passwordPrim.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                passwordPrimActionPerformed(evt);
            }
        });
        getContentPane().add(passwordPrim, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 150, 30));

        passwordConf.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                passwordConfActionPerformed(evt);
            }
        });
        getContentPane().add(passwordConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 160, 30));

        txtUsuario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 310, 30));

        registrar.setBackground(new java.awt.Color(51, 255, 51));
        registrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                registrarActionPerformed(evt);
            }
        });
        getContentPane().add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        limpia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        limpia.setText("Limpiar");
        limpia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                limpiaActionPerformed(evt);
            }
        });
        getContentPane().add(limpia, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtUsuarioActionPerformed
    {//GEN-HEADEREND:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_registrarActionPerformed
    {//GEN-HEADEREND:event_registrarActionPerformed
        if (txtID.getText().trim().isEmpty() || txtNombre.getText().trim().isEmpty() || txtDomicilio.getText().trim().isEmpty() || txtUsuario.getText().trim().isEmpty()
                || txtTelefono.getText().trim().isEmpty() || passwordPrim.getPassword().length == 0 || passwordConf.getPassword().length == 0
                || (!jRadioButton1.isSelected() && !jRadioButton2.isSelected()))
        {
            String id = txtID.getText();
            String nombre = txtNombre.getText();
            String direccion = txtDomicilio.getText();
            String usuario = txtUsuario.getText();
            String telefono = txtTelefono.getText();
            String contra = passwordPrim.getText();
            String contraConf = passwordConf.getText();

            String expID = "[0-9]{3}";
            String expNombre = "[A-Za-z]{20,50}";
            String expDireccion = "[a-zA-Z0-9]{100}";
            String expUsuario = "[a-zA-Z0-9]{10}";
            String expTelefono = "[0-9]{10}";
            String expContra = "[0-9a-z]{6}";
            String expContraConf = "[0-9a-z]{6}";

            Pattern patID = Pattern.compile(expID);
            Pattern patNombre = Pattern.compile(expNombre);
            Pattern patDireccion = Pattern.compile(expDireccion);
            Pattern patUsuario = Pattern.compile(expUsuario);
            Pattern patTelefono = Pattern.compile(expTelefono);
            Pattern patContra = Pattern.compile(expContra);
            Pattern patContraConf = Pattern.compile(expContraConf);

            Matcher matchID = patID.matcher(id);
            Matcher matchNombre = patNombre.matcher(nombre);
            Matcher matchDireccion = patDireccion.matcher(direccion);
            Matcher matchUsuario = patUsuario.matcher(usuario);
            Matcher matchTelefono = patTelefono.matcher(telefono);
            Matcher matchContra = patContra.matcher(contra);
            Matcher matchContraConf = patContraConf.matcher(contraConf);

            boolean validaID = matchID.matches();
            boolean validaNombre = matchNombre.matches();
            boolean validaDireccion = matchDireccion.matches();
            boolean validaUsuario = matchUsuario.matches();
            boolean validaTelefono = matchTelefono.matches();
            boolean validaContra = matchContra.matches();
            boolean validaContraConf = matchContraConf.matches();

            if (!validaID && !validaNombre && !validaDireccion && !validaUsuario && !validaTelefono && !validaContra && !validaContraConf)
            {
                JOptionPane.showMessageDialog(frameAdmin.this, "Hay campos vacios y/o están incorrectos", "Faltan datos", JOptionPane.WARNING_MESSAGE);
            }else
            {
                if (jRadioButton1.isSelected() || jRadioButton2.isSelected())
                {
                    tipoUsuario = (jRadioButton1.isSelected()) ? 1 : 0;                                        
                } else
                {
                    JOptionPane.showMessageDialog(frameAdmin.this, "Seleccione el tipo de usuario", "Faltan Tipo Usuario", JOptionPane.WARNING_MESSAGE);
                }
            }
        } else
        {
            JOptionPane.showMessageDialog(frameAdmin.this, "Registrando...", "Registrar", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void limpiaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_limpiaActionPerformed
    {//GEN-HEADEREND:event_limpiaActionPerformed
        limpiar();
    }//GEN-LAST:event_limpiaActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtIDActionPerformed
    {//GEN-HEADEREND:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtDomicilioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtDomicilioActionPerformed
    {//GEN-HEADEREND:event_txtDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomicilioActionPerformed

    private void passwordPrimActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_passwordPrimActionPerformed
    {//GEN-HEADEREND:event_passwordPrimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordPrimActionPerformed

    private void passwordConfActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_passwordConfActionPerformed
    {//GEN-HEADEREND:event_passwordConfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordConfActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton1ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    private void limpiar()
    {
        txtID.setText("");
        txtNombre.setText("");
        txtDomicilio.setText("");
        txtUsuario.setText("");
        txtTelefono.setText("");
        passwordPrim.setText("");
        passwordConf.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton limpia;
    private javax.swing.JPasswordField passwordConf;
    private javax.swing.JPasswordField passwordPrim;
    private javax.swing.JButton registrar;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
