/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vtnF;

/**
 *
 * @author Cassandra
 */
public class vtnPrincipal extends javax.swing.JFrame
{

    /**
     * Creates new form vtnProductos
     */
    public vtnPrincipal()
    {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Principal");
        this.btnProductos.requestFocus();
        if (vtnIngreso.tipoUsuario == 1)
        {
            btnReportes.setEnabled(false);
            jLabel12.setText("Ventas");
            altaEmp.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        btnProductos = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnAlmacen = new javax.swing.JButton();
        altaEmp = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        desktopPaneControl = new javax.swing.JDesktopPane();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/medico.png"))); // NOI18N
        btnProductos.setToolTipText("");
        btnProductos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/de-venta.png"))); // NOI18N
        btnVentas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/servicio-al-cliente.png"))); // NOI18N
        btnCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        btnAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gestion-de-materiales.png"))); // NOI18N
        btnAlmacen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAlmacenActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        altaEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contratacion.png"))); // NOI18N
        altaEmp.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                altaEmpActionPerformed(evt);
            }
        });
        jPanel1.add(altaEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/beneficio-financiero.png"))); // NOI18N
        btnReportes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        javax.swing.GroupLayout desktopPaneControlLayout = new javax.swing.GroupLayout(desktopPaneControl);
        desktopPaneControl.setLayout(desktopPaneControlLayout);
        desktopPaneControlLayout.setHorizontalGroup(
            desktopPaneControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneControlLayout.setVerticalGroup(
            desktopPaneControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(desktopPaneControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 620, 420));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario22.png"))); // NOI18N
        jLabel12.setText("Administrador");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Usuario (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlmacenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAlmacenActionPerformed
    {//GEN-HEADEREND:event_btnAlmacenActionPerformed
        desktopPaneControl.removeAll();
        frameAlmacen fA = new frameAlmacen();
        desktopPaneControl.add(fA).setVisible(true);
    }//GEN-LAST:event_btnAlmacenActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnProductosActionPerformed
    {//GEN-HEADEREND:event_btnProductosActionPerformed
        desktopPaneControl.removeAll();
        frameProductos fP = new frameProductos();
        desktopPaneControl.add(fP).setVisible(true);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnReportesActionPerformed
    {//GEN-HEADEREND:event_btnReportesActionPerformed
        desktopPaneControl.removeAll();
        frameReportes fR = new frameReportes();
        desktopPaneControl.repaint();
        desktopPaneControl.add(fR).setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnVentasActionPerformed
    {//GEN-HEADEREND:event_btnVentasActionPerformed
        desktopPaneControl.removeAll();
        frameVentas fV = new frameVentas();
        desktopPaneControl.add(fV).setVisible(true);
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClienteActionPerformed
    {//GEN-HEADEREND:event_btnClienteActionPerformed
        desktopPaneControl.removeAll();
        frameClientes fC = new frameClientes();
        desktopPaneControl.add(fC).setVisible(true);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void altaEmpActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_altaEmpActionPerformed
    {//GEN-HEADEREND:event_altaEmpActionPerformed
        desktopPaneControl.removeAll();
        frameAdmin fA = new frameAdmin();
        desktopPaneControl.add(fA).setVisible(true);
    }//GEN-LAST:event_altaEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new vtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaEmp;
    private javax.swing.JButton btnAlmacen;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnVentas;
    private javax.swing.JDesktopPane desktopPaneControl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
